package net.aevummc.jobs.gui;

import net.aevummc.jobs.AevumJobs;
import net.aevummc.jobs.config.ConfigManager;
import net.aevummc.jobs.database.Database;
import net.aevummc.jobs.job.JobData;
import net.aevummc.jobs.job.JobType;
import net.aevummc.jobs.reward.RewardService;
import net.aevummc.jobs.service.JobService;
import net.aevummc.jobs.service.PlayerJobs;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.TextColor;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.*;

public final class GuiManager {
    public enum Menu { MAIN, SELECT, MANAGE, CONFIRM, PROGRESSION, REWARDS, STATS, LEADERBOARD }
    public static final int[] JOB_SLOTS={10,12,14,16,19,21,23,25,28,30,32,34};
    private final AevumJobs plugin; private final ConfigManager config; private final JobService jobs; private final RewardService rewards;
    private final TextColor GOLD=TextColor.fromHexString("#FFC847"); private final TextColor BRONZE=TextColor.fromHexString("#C98B24");
    public GuiManager(AevumJobs plugin,ConfigManager config,JobService jobs,RewardService rewards){this.plugin=plugin;this.config=config;this.jobs=jobs;this.rewards=rewards;}
    public void openMain(Player p,PlayerJobs d){Inventory inv=Bukkit.createInventory(new Holder(Menu.MAIN,null,null),54,config.config().getString("gui.main-title","🏛 A E V U M • J O B S"));decorate(inv);addJobCards(inv,d);addActive(inv,d);inv.setItem(49,item(Material.BOOK,"§6§lYour Statistics",List.of("§7Every profession. Total XP. Total earned.","§eClick to view.")));inv.setItem(50,item(Material.LECTERN,"§6§lManage Professions",List.of("§7Change your active professions.","§eClick to manage.")));inv.setItem(52,item(Material.GOLD_INGOT,"§6§lLeaderboards",List.of("§7Top specialists across Aevum.","§eClick to view.")));inv.setItem(53,item(Material.BARRIER,"§cClose",List.of()));p.openInventory(inv);}
    public void openSelection(Player p,PlayerJobs d){Inventory inv=Bukkit.createInventory(new Holder(Menu.SELECT,null,null),54,config.config().getString("gui.selection-title","Choose Your Profession"));decorate(inv);addJobCards(inv,d);inv.setItem(45,item(Material.IRON_INGOT,"§6§lActive Slots",List.of("§7Used: §f"+d.activeCount()+"§7 / §f"+config.activeLimit())));inv.setItem(49,item(Material.ARROW,"§eBack",List.of()));inv.setItem(53,item(Material.BARRIER,"§cClose",List.of()));p.openInventory(inv);}
    public void openManage(Player p,PlayerJobs d){Inventory inv=Bukkit.createInventory(new Holder(Menu.MANAGE,null,null),54,config.config().getString("gui.manage-title","Manage Your Professions"));decorate(inv);int slot=20;for(JobType j:d.active()){JobData jd=d.get(j);inv.setItem(slot++,item(j.getMaterial(),"§6§l"+j.getIcon()+" "+j.getDisplayName(),List.of("§7Level: §f"+jd.level(),"§7XP: §f"+Math.round(jd.xp()),"","§eLeft click §7to view","§cRight click §7to leave")));}inv.setItem(49,item(Material.ARROW,"§eBack",List.of()));inv.setItem(53,item(Material.BARRIER,"§cClose",List.of()));p.openInventory(inv);}
    public void openConfirm(Player p,PlayerJobs d,JobType j){Inventory inv=Bukkit.createInventory(new Holder(Menu.CONFIRM,j,null),27,"§8Leave "+j.getDisplayName()+"?");decorate(inv);JobData jd=d.get(j);inv.setItem(11,item(j.getMaterial(),"§c§lLEAVE "+j.getDisplayName(),List.of("§7Your progression will be preserved.","","§7Level: §f"+jd.level(),"§7XP: §f"+Math.round(jd.xp()),"§7Total earned: §f$"+String.format("%,.0f",jd.totalEarned()))));inv.setItem(15,item(Material.LIME_CONCRETE,"§a§l✓ CONFIRM",List.of()));inv.setItem(13,item(Material.RED_CONCRETE,"§c§l✕ CANCEL",List.of()));p.openInventory(inv);}
    public void openProgression(Player p,PlayerJobs d,JobType j){Inventory inv=Bukkit.createInventory(new Holder(Menu.PROGRESSION,j,null),54,config.config().getString("gui.progress-title","✦ Profession Progression"));decorate(inv);JobData jd=d.get(j);inv.setItem(4,item(j.getMaterial(),"§6§l"+j.getIcon()+" "+j.getDisplayName(),List.of("§7"+j.getDescription(),"","§fLevel §6§l"+jd.level(),"§7XP §f"+Math.round(jd.xp())+" / "+reqText(jd.level()))));int[] ms={10,19,28,37,46,52};int[] levels={1,10,20,30,40,50};for(int i=0;i<levels.length;i++){int l=levels[i];String state=jd.level()>l?"§a✓ Completed":jd.level()==l?"§6★ Current":"§8🔒 Locked";inv.setItem(ms[i],item(l<=jd.level()?Material.GOLD_BLOCK:Material.IRON_BLOCK,"§6§lLEVEL "+l,List.of(state,"§7Cash: §f"+money(config.cashReward(l)),l==50?"§7Master Reward: §e"+masterName(j):"§7Progress milestone")));}inv.setItem(31,item(Material.EXPERIENCE_BOTTLE,"§6§lPROGRESS",List.of(progressBar(jd),"§7Total XP: §f"+jd.totalXp(),"§7Actions: §f"+jd.actions())));inv.setItem(41,item(Material.CHEST,"§6§lVIEW ALL REWARDS",List.of("§7See all 50 level rewards.","§eClick"));if(d.isActive(j))inv.setItem(43,item(Material.RED_CONCRETE,"§c§lLEAVE PROFESSION",List.of("§7Progression will be preserved.","§eClick to manage")));else inv.setItem(43,item(Material.LIME_CONCRETE,"§a§lJOIN PROFESSION",List.of(d.activeCount()>=config.activeLimit()?"§c3/3 PROFESSIONS ACTIVE":"§7Activate this profession","§eClick to join")));inv.setItem(49,item(Material.ARROW,"§eBack",List.of()));inv.setItem(53,item(Material.BARRIER,"§cClose",List.of()));p.openInventory(inv);}
    public void openRewards(Player p,PlayerJobs d,JobType j){openRewards(p,d,j,0);}
    public void openRewards(Player p,PlayerJobs d,JobType j,int page){Inventory inv=Bukkit.createInventory(new Holder(Menu.REWARDS,j,null,page),54,config.config().getString("gui.rewards-title","Profession Rewards"));decorate(inv);int startLevel=page*45+1;int endLevel=Math.min(50,startLevel+44);for(int l=startLevel;l<=endLevel;l++){int slot=9+((l-startLevel)%45);String s=d.get(j).level()>=l?"§a✓ REACHED":"§8🔒 Locked";if(d.get(j).level()==l)s="§6★ CURRENT";String extra=l==50?"§e+ Master Reward":"§7Money only";inv.setItem(slot,item(l==50?Material.NETHER_STAR:Material.GOLD_NUGGET,"§6§lLEVEL "+l,List.of("§7Cash: §f"+money(config.cashReward(l)),extra,s)));}if(page>0)inv.setItem(48,item(Material.ARROW,"§ePrevious",List.of("§7Page "+page)));if(endLevel<50)inv.setItem(50,item(Material.ARROW,"§eNext",List.of("§7Page "+(page+2))));if(d.get(j).level()>=50&&!d.get(j).level50Rewarded())inv.setItem(49,item(Material.NETHER_STAR,"§6§l⭐ CLAIM MASTER REWARD",List.of("§7Make one inventory space.","§eClick to claim")));else inv.setItem(49,item(Material.GOLD_BLOCK,"§6§lMASTER REWARD",List.of(d.get(j).level50Rewarded()?"§a✓ Claimed":"§8Reach Level 50")));inv.setItem(53,item(Material.ARROW,"§eBack",List.of()));p.openInventory(inv);}
    public void openStats(Player p,PlayerJobs d){Inventory inv=Bukkit.createInventory(new Holder(Menu.STATS,null,null),54,config.config().getString("gui.stats-title","AevumJobs Statistics"));decorate(inv);int slot=10;for(JobType j:JobType.values()){JobData jd=d.get(j);inv.setItem(slot++,item(j.getMaterial(),"§6§l"+j.getIcon()+" "+j.getDisplayName(),List.of("§7Level: §f"+jd.level(),"§7XP: §f"+Math.round(jd.xp()),"§7Total XP: §f"+jd.totalXp(),"§7Actions: §f"+jd.actions(),"§7Earned: §f"+money(jd.totalEarned()))));if(slot==17)slot=19;if(slot==26)slot=28;if(slot==35)slot=37;if(slot==44)break;}int highest=d.all().stream().mapToInt(JobData::level).max().orElse(0);long totalXp=d.all().stream().mapToLong(JobData::totalXp).sum();double totalEarned=d.all().stream().mapToDouble(JobData::totalEarned).sum();inv.setItem(49,item(Material.EXPERIENCE_BOTTLE,"§6§lACCOUNT TOTALS",List.of("§7Active: §f"+d.activeCount()+" / "+config.activeLimit(),"§7Highest Level: §f"+highest,"§7Total XP: §f"+totalXp,"§7Total Earned: §f"+money(totalEarned))));inv.setItem(53,item(Material.ARROW,"§eBack",List.of()));p.openInventory(inv);}
    public void openLeaderboard(Player p,PlayerJobs d){Inventory inv=Bukkit.createInventory(new Holder(Menu.LEADERBOARD,null,null),54,config.config().getString("gui.leaderboard-title","AevumJobs Leaderboards"));decorate(inv);List<JobType> types=List.of(JobType.values());for(int i=0;i<types.size();i++){JobType j=types.get(i);inv.setItem(JOB_SLOTS[i],item(j.getMaterial(),"§6§l"+j.getIcon()+" "+j.getDisplayName(),List.of("§7Loading top specialists...")));final int s=JOB_SLOTS[i];plugin.getDatabase().leaderboard(j,3).thenAccept(list->Bukkit.getScheduler().runTask(plugin,()->{if(!p.isOnline())return;Inventory cur=p.getOpenInventory().getTopInventory();if(!(cur.getHolder() instanceof Holder h)||h.menu()!=Menu.LEADERBOARD)return;List<String> lore=new ArrayList<>();if(list.isEmpty())lore.add("§8No ranked players yet.");int rank=1;for(Database.LeaderboardEntry e:list){org.bukkit.OfflinePlayer op=Bukkit.getOfflinePlayer(e.uuid());String medal=rank==1?"§e🥇":rank==2?"§f🥈":rank==3?"§6🥉":"§7"+rank;lore.add(medal+" §f"+(op.getName()==null?e.uuid().toString().substring(0,8):op.getName())+" §7• §fLv."+e.level());rank++;}cur.setItem(s,item(j.getMaterial(),"§6§l"+j.getIcon()+" "+j.getDisplayName(),lore));}));}inv.setItem(53,item(Material.ARROW,"§eBack",List.of()));p.openInventory(inv);}
    private void addJobCards(Inventory inv,PlayerJobs d){for(int i=0;i<JobType.values().length;i++){JobType j=JobType.values()[i];JobData jd=d.get(j);String status=d.isActive(j)?"§a● ACTIVE":"§8○ INACTIVE";inv.setItem(JOB_SLOTS[i],item(j.getMaterial(),"§6§l"+j.getIcon()+" "+j.getDisplayName(),List.of("§7"+j.getDescription(),"",status,"§7Level: §f"+jd.level(),"§7XP: §f"+Math.round(jd.xp())+" / "+reqText(jd.level()),"§7Progress: §f"+progressPct(jd),"§7Total Earned: §f"+money(jd.totalEarned()),"","§eClick to view")));}}
    private void addActive(Inventory inv,PlayerJobs d){int[] slots={45,46,47};Set<JobType> a=d.active();int i=0;for(JobType j:a){JobData jd=d.get(j);inv.setItem(slots[i++],item(j.getMaterial(),"§6§l"+j.getIcon()+" "+j.getDisplayName(),List.of("§7Level: §f"+jd.level(),"§7XP: §f"+Math.round(jd.xp()),"§eClick to view")));}while(i<3)inv.setItem(slots[i++],item(Material.GRAY_STAINED_GLASS_PANE,"§8＋ Empty Profession Slot",List.of("§7Click to choose a profession.")));}
    private void decorate(Inventory inv){for(int s:new int[]{0,1,2,3,5,6,7,8,9,17,18,26,27,35,36,44,45,48,51,52})inv.setItem(s,item(Material.BLACK_STAINED_GLASS_PANE,"§8",List.of()));}
    private ItemStack item(Material mat,String name,List<String> lore){ItemStack x=new ItemStack(mat);ItemMeta m=x.getItemMeta();m.displayName(Component.text(ChatColor.stripColor(name),GOLD));List<Component> l=new ArrayList<>();for(String line:lore)l.add(Component.text(ChatColor.stripColor(line),line.contains("§6")?BRONZE:TextColor.fromHexString("#BDBDBD")));m.lore(l);x.setItemMeta(m);return x;}
    private String reqText(int level){return level>=50?"MAX":String.format("%,.0f XP",config.requiredXp(level));}private String money(double v){return String.format("$%,.0f",v);}private String progressPct(JobData j){if(j.level()>=50)return "100%";return String.format("%.0f%%",j.xp()/config.requiredXp(j.level())*100);}private String progressBar(JobData j){if(j.level()>=50)return "§6████████████████████ 100%";int filled=(int)Math.round(Math.min(1,j.xp()/config.requiredXp(j.level()))*20);return "§6"+"█".repeat(filled)+"§8"+"░".repeat(20-filled)+" §f"+progressPct(j);}private String masterName(JobType j){return config.config().getString("master-rewards."+j.key()+".name","Master "+j.getDisplayName());}
    public static final class Holder implements InventoryHolder {private final Menu menu;private final JobType job;private final UUID target;private final int page;public Holder(Menu m,JobType j,UUID t){this(m,j,t,0);}public Holder(Menu m,JobType j,UUID t,int page){menu=m;job=j;target=t;this.page=page;}public Menu menu(){return menu;}public JobType job(){return job;}public UUID target(){return target;}public int page(){return page;}public Inventory getInventory(){return null;}}
}